kind: Pod
apiVersion: v1
metadata:
  name: default-ns-app
  namespace: default
spec:
  containers:
    - image: yoavklein3/net-tools:latest
      name: demo-app
      command: ["bash", "-c", 'while true; do echo \{\"data\":\"This is from default namespace\"}; sleep 2; done']
---
kind: Namespace
apiVersion: v1
metadata:
  name: foo
---
kind: Pod
apiVersion: v1
metadata:
  name: foo-ns-app
  namespace: foo
spec:
  containers:
    - image: yoavklein3/net-tools:latest
      name: demo-app
      command: ["bash", "-c", 'while true; do echo \{\"data\":\"This is from FOO namespace\"}; sleep 2; done']
---
kind: Namespace
apiVersion: v1
metadata:
  name: bar
---
kind: Pod
apiVersion: v1
metadata:
  name: bar-ns-app
  namespace: bar
spec:
  containers:
    - image: yoavklein3/net-tools:latest
      name: demo-app
      command: ["bash", "-c", 'while true; do echo \{\"data\":\"This is from FOO namespace\"}; sleep 2; done']

