kind: ConfigMap
apiVersion: v1
metadata:
  namespace: kube-system
  name: fluentd-tls
data:
  client.crt: |+
    -----BEGIN CERTIFICATE-----
    MIIDMzCCAhsCFA8OEdhTw4l9XPUyUwjOGdKwPO+eMA0GCSqGSIb3DQEBCwUAMFcx
    CzAJBgNVBAYTAklMMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRl
    cm5ldCBXaWRnaXRzIFB0eSBMdGQxEDAOBgNVBAMMB2V4YW1wbGUwHhcNMjMwNDI0
    MTg1MjM5WhcNMjQwNDIzMTg1MjM5WjBVMQswCQYDVQQGEwJJTDETMBEGA1UECAwK
    U29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMQ4w
    DAYDVQQDDAVhZG1pbjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAK3k
    4bcdtSqqc8Xe9cbSr1odnblQU4q1+ApUmxFVHd4H9Wb2cPu6DCchb1DtvhaLF3Ti
    99Wdgoq5UE3OLBX9+lyrM7Uc2BPKgRpvVuYpmIeYuk2bAGZWRB9YRZ9hM5SHzVfm
    XHNabNXFZbYkDhXBoER+LlDVAC8oXaneg69scBRQIYNPoCGna5Ky71jvqm3Sp9VM
    t0g4jjQDie2Y88jWf5XnJOo6uil6Xy+3iZ9GthGjdWgiYnfv780dr6V+9sX5qlmV
    34pOBlYS1w2bkveliZlW7H+Cc+JTbfxwST1rR8a4W+vr2gm0LdLD4LuVaeAfnyV8
    3PprDvgKiP8BQFSDXcsCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAnY/teZerzswp
    D2PjHco6I6YIGtv//18wo7Lp7VWxUVHvEGcLMVjl3cc1lku8wIr3U3tRM7Jvd/ay
    /7nQtKKo4hLPiYa3ZRCJaNN/6QG3hzKaGdfPWFKhUBzLd/SEKnbL+WV/JcIUoaMn
    hh3pUmIEWW5IHDv0OSSc07F2z6Apt2MXs823dbNXWflP2gOp0ZeqOq50SUDQqfEf
    U/1RF7l56HonDdaJaJeZvpgapS7L/GRWg19MKel25QAllaqPQEGYhbgiuNkWP2r+
    9378q2/Gv5jX8mdV/35JAUUFQWKx05rypAYP7/oeAxlsP5nzh/RgUKNQK7WIRYBT
    +lTF8T/CPg==
    -----END CERTIFICATE-----
  client.key: |+
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCt5OG3HbUqqnPF
    3vXG0q9aHZ25UFOKtfgKVJsRVR3eB/Vm9nD7ugwnIW9Q7b4Wixd04vfVnYKKuVBN
    ziwV/fpcqzO1HNgTyoEab1bmKZiHmLpNmwBmVkQfWEWfYTOUh81X5lxzWmzVxWW2
    JA4VwaBEfi5Q1QAvKF2p3oOvbHAUUCGDT6Ahp2uSsu9Y76pt0qfVTLdIOI40A4nt
    mPPI1n+V5yTqOropel8vt4mfRrYRo3VoImJ37+/NHa+lfvbF+apZld+KTgZWEtcN
    m5L3pYmZVux/gnPiU238cEk9a0fGuFvr69oJtC3Sw+C7lWngH58lfNz6aw74Coj/
    AUBUg13LAgMBAAECggEAIG5L1EljlMH2VoRXBQ4c6usUE9ARzJBUYqTVyL09lT+Z
    umqitqfDhXa8WnUEWxL0vHVp8DpwcqvN+LzHRxC3ZRn+yjvHZqWBP2tdYw6F5mAK
    +tc6E1vqV4gwb+GCa6SKHOcW/eJy4sluRzJhOBiE6dE4lRWsc58NHNWlbI2GN5tN
    Pug6ur2wReLKVAQmEUCSNYZH9vXOmMqJKwkiHEePpJfoOVWjfcCOcBa0QbPQSUOG
    s5w4Gevr5UBQnzrV6N+56u+K4CF75LVayeQJxygE54lowSOQH7U3tMFJ+7gzUjS+
    hf8v4Su0GlB1SuqMzPP1DfJn/MV3dFygaVYXzcP+eQKBgQDjup81Xk0+blMupVgz
    EoBz4YEAIMGJAzHKhsw91LOyFzKo1fYekm3VnvFQqVS8wBXP7IFh/K4XjpL7OQwt
    aEcM9EgYssmPhByzDa7oJKUf6HifIDrNiYM57IxD6KwsA/S7og/mpno7brni94E5
    GxReFLKZtmBWwGIMoVKW47Oi2QKBgQDDe1muV7prEHmYJ/ZjGuGHvZ8tGcrqCJIe
    H6y22Hwn1n6uTNfgJS473fl6ZRE8CYRY+oE5Ur0ZaTZ6KgsQat6HxEI6whqo+rcY
    pyHCX2503SZjhT8ZRt3kiNkafupWiMwtZncyj4XzT94kBkoLxTTEVxprqjkQ7Ekz
    jS91yGhXQwKBgHLrSkx0Oia3JeL0LX4YaBoSQjb+UKwDoKzDOW46WDQW4Mmyr3De
    E+8pNj2uNcTKajdy8hewm2nn2ORN9Yc0iCZRX9CW6IAz+wegcBNV6r4fYj9q1EHE
    kyQ36tCaKchMdsP5FG0gta4oQkX3AI8Ay1Zuu3I2RoeArfoRrsvWPGCBAoGAOtB0
    DRZsCiZszzDG2s6NqI+Owr0N5hgqDlItXt4HjNzmRH7uPIwzOuPwWbjq1ItwfGzy
    UFLqfii/sUXRCmF9DpAn9RHNf6XfTNWMPLUFwLeBA1Rlxa8it83MtEIXM235MHex
    yU6RWMFg7qnNwXjWBXTHiDkw7jyJUa9a5i8j5Y0CgYAY7G92r7ZuV1qGeLfoh9Hx
    EvMtVnGkmw8VMgoEoiEVstBNJIPkV40gvBM5S0r2D7mjJ6OeMriRRHzxEj09ejNB
    GY2bDkDHADWaAgYeBxGHlwZTedFmoktebXehNh52Wa/mC5DbdqaV6APwC91Pl6M/
    q77WBtcmYqQKc5/8G2sZgw==
    -----END PRIVATE KEY-----
  ca.crt: |+
    -----BEGIN CERTIFICATE-----
    MIIDjzCCAnegAwIBAgIURQ3Ejip14SxUMUnxhCdVlk56prkwDQYJKoZIhvcNAQEL
    BQAwVzELMAkGA1UEBhMCSUwxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEQMA4GA1UEAwwHZXhhbXBsZTAeFw0y
    MzA0MjQxODQ4MjRaFw0yNDA0MjMxODQ4MjRaMFcxCzAJBgNVBAYTAklMMRMwEQYD
    VQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBM
    dGQxEDAOBgNVBAMMB2V4YW1wbGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQDHOFdLuPS/cXx0Qt0dlndkOGNNGA1t38DZusg5pcVvsl57pD+iXGror5d0
    iBX2Hmx21i31FCRXktzmNjhEvT22WPGJVZpCND9gsk8+abY3oWAd5tEumSSbY2Z0
    apOY7a9o3RXcXV7iM6U/pailcyhQFBvoDhYHFfKBSScpdN3bpypK2Hp8goqeuweQ
    ciEgZcvjEshJwy9jPhsHHAEtBrwjSDMHWdMnohAl6rG/wpwwzsV53pUGJn4EJIxl
    g3HzBTgfspppA7GJDBZQCVjPOSTBk6+8HQtYHylQWo7BAWw+XlVeuE9WfTtyFwNR
    6zeB05U6roSXLpuAce5Pm6FNMdipAgMBAAGjUzBRMB0GA1UdDgQWBBQCtu8zxE3E
    VLIdV3LDJjgKq8FgHDAfBgNVHSMEGDAWgBQCtu8zxE3EVLIdV3LDJjgKq8FgHDAP
    BgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBLCJG0NZwLeuVbfduv
    jggaWYFb83ggU14y6AL3YwxDFAcPm0zBM0RI0QJk7pdSFnGBRjbaoVW+5k5Or0TG
    DcCSI2Eph0WJyt2vQNrZGZQjhACzGfncHGdQlnTbWac8js1h7bP6Z6I1Hf/85gNI
    9oHS1FX0TF8fn8mEbtaWbEkwcNhyzw4WrsU29PuWxvFzyDqWGfZQKJDm0RTNcUO8
    J3xw59jkegNAhopi/btbuYOvbYeDRrPLAD25WAreB9jxj5DNj0u8hYXpCMJU3i8n
    Z7tBXUoujOom4bUereb0ywjc2AVAY+hz7VYSlSo6g1EDy6JUt0LN7McW1kx++xIb
    y0vv
    -----END CERTIFICATE-----
