kind: Pod
apiVersion: v1
metadata:
  name: default-ns-app
  namespace: default
spec:
  containers:
    - image: yoavklein3/net-tools:latest
      name: demo-app
      command: ["bash", "-c", 'while true; do echo \{\"data\":\"Some important log\"}; sleep 2; done']


