apiVersion: v1
kind: Pod
metadata:
  name: debug-tls
  namespace: storage
spec:
  containers:
  - image: yoavklein3/net-tools:0.3
    name: debug-tls
    command: ["sleep", "3600"]
    volumeMounts:
      #    - name: tls
      # mountPath: /usr/share/opensearch/config/tls
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
    - name: varlog
      mountPath: /var/log
  volumes:
    # - name: tls
    #  configMap:
    #    name: opensearch-tls
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
    - name: varlog
      hostPath:
        path: /var/log


