
apiVersion: v1
kind: Namespace
metadata:
  name: storage
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: storage
spec:
  ports:
  - targetPort: 9200
    port: 9200
    name: opensearch
  selector:
    app: opensearch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: storage
spec:
  selector:
    matchLabels:
      app: opensearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      containers:
      - image: opensearchproject/opensearch:1.3.9
        name: opensearch
        volumeMounts:
          - name: tls
            mountPath: /usr/share/opensearch/config/tls
        env:
          - name: discovery.type
            value: 'single-node'
          - name: plugins.security.disabled
            value: "false"
          - name: plugins.security.ssl.http.pemkey_filepath
            value: "tls/server.key"
          - name: plugins.security.ssl.http.pemcert_filepath
            value: "tls/server.crt"
          - name: plugins.security.ssl.http.pemtrustedcas_filepath
            value: "tls/ca.crt"

      volumes:
        - name: tls
          configMap:
            name: opensearch-tls


