version: "3"
services:
 fluentd:
    container_name: fluentd
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "9880:9880"
      - "9881:9881"
    networks:
      - opensearch-net

networks:
  opensearch-net:


