kind: Pod
apiVersion: v1
metadata:
  name: demo-app
  namespace: default
spec:
  containers:
    - image: yoavklein3/net-tools:latest
      name: demo-app
      command: ["bash", "-c", 'while true; do echo \{\"data\":\"kuku\"}; sleep 2; done']
