kind: Pod
apiVersion: v1
metadata:
  name: test
spec:
  containers:
    - image: yoavklein3/net-tools:latest
      name: test
      command: ["sleep", "3600"]
      volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
  volumes:
    - name: varlog
      hostPath:
        path: /var/log
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers

